# Generated by Django 5.0.6 on 2024-06-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='date',
        ),
        migrations.AddField(
            model_name='journal',
            name='template',
            field=models.CharField(choices=[('P', 'Personal'), ('T', 'Travel'), ('H', 'Wellness'), ('W', 'Work')], default='P', max_length=1),
        ),
    ]
