# Generated by Django 5.0.6 on 2024-06-05 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_journal_date_journal_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('body', models.CharField(max_length=1000)),
                ('notes', models.CharField(max_length=300)),
                ('mood_tracker', models.CharField(max_length=25)),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.journal')),
            ],
        ),
    ]
