# Generated by Django 5.0.6 on 2024-06-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='journal_id',
            new_name='journal',
        ),
    ]
