# Generated by Django 5.0.6 on 2024-06-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_travel_created_at_travel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travel',
            options={'ordering': ['-updated_at']},
        ),
    ]
