# Generated by Django 5.0.6 on 2024-06-07 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_travel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Wellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('body', models.TextField(max_length=1000)),
                ('notes', models.TextField(max_length=300)),
                ('affirmation', models.TextField(max_length=200)),
                ('food', models.CharField(max_length=50)),
                ('sleep', models.IntegerField()),
                ('mood', models.CharField(choices=[('H', 'Happy 😊'), ('S', 'Sad 😢'), ('C', 'Content 😌'), ('A', 'Angry 😡'), ('T', 'Tired 🥱'), ('X', 'Anxious 😰'), ('K', 'Sick 🤒')], default='H', max_length=1)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.journal')),
            ],
        ),
    ]
