# Generated by Django 5.0.6 on 2024-06-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_entry_options_alter_journal_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='mood_tracker',
        ),
        migrations.RemoveField(
            model_name='travel',
            name='mood_tracker',
        ),
        migrations.AddField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('H', 'Happy 😊'), ('S', 'Sad 😢'), ('C', 'Content 😌'), ('A', 'Angry 😡'), ('T', 'Tired 🥱'), ('X', 'Anxious 😰'), ('K', 'Sick 🤒')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='travel',
            name='mood',
            field=models.CharField(choices=[('H', 'Happy 😊'), ('S', 'Sad 😢'), ('C', 'Content 😌'), ('A', 'Angry 😡'), ('T', 'Tired 🥱'), ('X', 'Anxious 😰'), ('K', 'Sick 🤒')], default='H', max_length=1),
        ),
    ]
