# Generated by Django 5.0.6 on 2024-06-07 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_entry_mood_tracker_remove_travel_mood_tracker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.travel')),
            ],
        ),
    ]
