# Generated by Django 5.0.6 on 2024-06-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='travel',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='travel',
            name='food',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='travel',
            name='notes',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='wellness',
            name='food',
            field=models.TextField(max_length=150),
        ),
    ]
